branch: master
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "@semantic-release/npm"
    - npmPublish: false
  - - "@semantic-release/exec"
    - prepareCmd: 'echo "${nextRelease.notes}" > src/main/play/release-notes/en-US/default.txt'
      publishCmd: "./.github/scripts/publish-to-play-store.sh ${nextRelease.version}"
